{/*CREATE TABLE [dbo].[Compra](
	[idCompra] [int] IDENTITY(1,1) NOT NULL,
	[idCuentaCorriente] [int] NULL,
	[idPagoLot] [int] NULL,
	[idAsiRet] [int] NULL,
	[idAsientoPer] [int] NULL,
	[idCliente] [int] NULL,
	[idAsiento] [int] NULL,
	[idPorcIce] [int] NULL,
	[idProyecto] [int] NULL,
	[idSubProyecto] [int] NULL,
	[idOrdenProd] [int] NULL,
	[idFormaPago] [int] NULL,
	[idEmpleado] [int] NULL,
	[idTipoFactura] [int] NULL,
	[idBanco] [int] NULL,
	[idVendedor] [int] NULL,
	[idTipoMoneda] [int] NULL,
	[idComprobante] [int] NULL,
	[idCredTributario] [int] NULL,
	[idSucursal] [int] NOT NULL,
	[idRecibe] [int] NULL,
	[Fecha] [datetime] NULL,
	[FechaIngreso] [datetime] NULL,
	[FechaVencimiento] [datetime] NULL,
	[Usuario] [varchar](50) NULL,
	[Numero] [varchar](50) NULL,
	[Notas] [varchar](8000) NULL,
	[Total] [decimal](18, 4) NULL,
	[Desc1] [float] NULL,
	[Desc2] [float] NULL,
	[Desc3] [float] NULL,
	[Desc4] [float] NULL,
	[Descuento] [decimal](18, 4) NULL,
	[Descuento0] [decimal](18, 4) NULL,
	[Iva] [decimal](18, 4) NULL,
	[Interes] [decimal](18, 4) NULL,
	[DiasCredito] [int] NULL,
	[Contado] [float] NULL,
	[Credito] [float] NULL,
	[Saldo] [float] NULL,
	[NumCheque] [varchar](50) NULL,
	[NumCuenta] [varchar](50) NULL,
	[ContadoCredito] [int] NULL,
	[NumCuotas] [int] NULL,
	[ValorCuotas] [decimal](18, 4) NULL,
	[TotalCuotas] [decimal](18, 4) NULL,
	[ValorDolar] [float] NULL,
	[PorcentajeIva] [float] NULL,
	[ValorInteres] [float] NULL,
	[FechaRevision] [datetime] NULL,
	[Revisado] [bit] NOT NULL,
	[Entregado] [bit] NOT NULL,
	[FechaEntrega] [datetime] NULL,
	[Otro] [varchar](100) NULL,
	[SubtotalIva] [decimal](18, 4) NULL,
	[SubtotalExcento] [decimal](18, 4) NULL,
	[Retencion] [bit] NOT NULL,
	[DerechoDevolucion] [bit] NOT NULL,
	[Ice] [float] NULL,
	[Refrendo] [varchar](50) NULL,
	[Comprobante] [varchar](8000) NULL,
	[Bodega] [int] NULL,
	[Flete] [float] NULL,
	[PagosCada] [int] NULL,
	[DiasInicio] [int] NULL,
	[AutImprenta] [varchar](50) NULL,
	[AutFactura] [varchar](100) NULL,
	[SerieFactura] [varchar](50) NULL,
	[DescPorcIva0] [float] NULL,
	[DescPorcIva] [float] NULL,
	[Departamento] [varchar](50) NULL,
	[Prioridad] [int] NULL,
	[AutPrincipal] [bit] NOT NULL,
	[AutPresupuesto] [bit] NOT NULL,
	[Mensaje1] [varchar](230) NULL,
	[Mensaje2] [varchar](230) NULL,
	[Mensaje3] [varchar](230) NULL,
	[Nombre] [varchar](100) NULL,
	[Ruc] [varchar](15) NULL,
	[FletePorcentaje] [float] NULL,
	[Impreso] [bit] NOT NULL,
	[Nuevo] [bit] NOT NULL,
	[Editar] [bit] NOT NULL,
	[Borrar] [bit] NOT NULL,
	[Retenido] [decimal](18, 4) NULL,
	[CentroCosto] [varchar](50) NULL,
	[BienServicio] [int] NULL,
	[ConvenioInternac] [bit] NULL,
	[Vuelto] [float] NULL,
	[FechaEditado] [datetime] NULL,
	[FechaCaducidad] [datetime] NULL,
	[IvaServicio] [float] NULL,
	[CuentaRetDet] [int] NULL,
	[Comprob1] [varchar](20) NULL,
	[Depart] [varchar](50) NULL,
	[Pedido] [varchar](50) NULL,
	[Bulto] [varchar](50) NULL,
	[Peso] [varchar](50) NULL,
	[idImportacionTipo] [int] NULL,
	[Estacion] [varchar](50) NULL,
	[PagoAutorizado] [float] NULL,
	[idPagoAut] [int] NULL,
	[Bloquear] [bit] NULL,
	[Cif] [float] NULL,
	[CifIva] [float] NULL,
	[idAsientoLote] [int] NULL,
	[Servicio] [decimal](18, 2) NULL,
	[Propina] [float] NULL,
	[AutoImpSRI] [bit] NULL,
	[Comision] [float] NULL,
	[idNiffIngProv] [int] NULL,
	[NiifValorIng] [float] NULL,
	[IntImplicito] [float] NULL,
	[TasaCambio] [float] NULL,
	[idAsientoDif] [int] NULL,
	[subTotal] [float] NULL,
	[Dias2] [int] NULL,
	[Interes2] [float] NULL,
	[idComisionConfiteca] [int] NULL,
	[NotasAux] [varchar](4000) NULL,
	[Numero2] [varchar](25) NULL,
	[Garantia] [int] NULL,
	[tipoObra] [int] NULL,
	[nivePrioridadRuta] [int] NULL,
	[sistemaMonitoreado] [int] NULL,
	[sistemaSeguridad] [int] NULL,
	[idAsientoNIIF] [int] NULL,
	[idOrdenCompra] [int] NULL,
	[FactAfectaCosto] [varchar](20) NULL,
	[idCompraCosto] [int] NULL,
	[P_AnticipoV] [float] NULL,
	[P_MultasV] [float] NULL,
	[P_FondoGV] [float] NULL,
	[P_AnticipoP] [float] NULL,
	[P_MultasP] [float] NULL,
	[P_FondoGP] [float] NULL,
	[P_AnticipoT] [float] NULL,
	[P_MultasT] [float] NULL,
	[P_FondoGT] [float] NULL,
	[jm] [varchar](50) NULL,
	[jmc] [varchar](50) NULL,
	[IngAfectaCostoNiif] [bit] NULL,
	[P_FaltaRetencion] [bit] NULL,
	[P_FaltaOriginal] [bit] NULL,
	[BodegaD] [int] NULL,
	[Aprobado] [bit] NULL,
	[CuotaAsignada] [decimal](18, 4) NULL,
	[CuotaDisponible] [decimal](18, 4) NULL,
	[CuotaEntrada] [decimal](18, 4) NULL,
	[CuotaUsada] [decimal](18, 4) NULL,
	[FechaPrimerPago] [datetime] NULL,
	[IRBP] [float] NULL,
	[P_IdOrigen] [int] NULL,
	[Procesado] [bit] NULL,
	[Aprobada] [bit] NULL,
	[PrimerPago] [varchar](30) NULL,
	[FechaTentativaLlegada] [datetime] NULL,
	[Estado] [int] NULL,
	[NumeroSRI] [varchar](25) NULL,
	[Manual] [bit] NULL,
	[CrediPoint] [bit] NULL,
	[idTipoRuc] [int] NULL,
	[SaldoAnticipo] [decimal](18, 4) NULL,
	[Fiscal] [bit] NULL,
	[idMotivo] [int] NULL,
	[HoraLlegada] [datetime] NULL,
	[Efectivo] [float] NULL,
	[Import] [bit] NULL,
	[BodegaDestino] [int] NULL,
	[Observaciones] [varchar](8000) NULL,
	[idOrigen] [int] NULL,
	[HoraEntrega] [datetime] NULL,
	[idDireccion] [int] NULL,
	[idTipoCredito] [int] NULL,
	[Consignacion] [bit] NULL,
	[FechaAnulacion] [datetime] NULL,
	[FechaAprobacion] [datetime] NULL,
	[FechaRechazado] [datetime] NULL,
	[idTipoDePago] [int] NULL,
	[DiasCredito1] [int] NULL,
	[DiasCredito2] [int] NULL,
	[MaximoCredito] [decimal](18, 4) NULL,
	[Transferencia] [int] NULL,
	[idTipoFormaPago] [int] NULL,
	[ActualizaSaldo] [int] NULL,
	[SaldoInicial] [bit] NULL,
	[idOrigen1] [int] NULL,
	[FechaDevolucion] [datetime] NULL,
	[idCiudad] [int] NULL,
	[Proyecto] [varchar](20) NULL,
	[idProyectoZoom] [int] NULL,
	[NumDocAntiguo] [varchar](50) NULL,
	[Anticipo] [float] NULL,
	[UsuarioEnvio] [varchar](50) NULL,
	[UsuarioRecibido] [varchar](50) NULL,
	[idEntidadFinanciera] [int] NULL,
	[NumeroLote] [int] NULL,
	[idAsientoLoteSolidario] [int] NULL,
	[CapturaLote] [bit] NULL,
	[ORIGEN] [int] NULL,
	[RetenidoIVA] [decimal](18, 4) NULL,
	[RetenidoRenta] [decimal](18, 4) NULL,
	[DIFERIDO] [bit] NULL,
	[idTarjeta] [int] NULL,
	[idPlan] [int] NULL,
	[idPlazo] [int] NULL,
	[idInstitucion] [int] NULL,
	[idAsientoCCP] [int] NULL,
	[FechaRecepcion] [datetime] NULL,
	[EnviaBco] [int] NULL,
	[TipoEgreso] [int] NULL,
	[Sel] [bit] NULL,
	[Saldo1] [float] NULL,
	[FechaEnvioBco] [date] NULL,
	[idCobrador] [int] NULL,
	[FechaGestion] [datetime] NULL,
	[Bloqueado] [bit] NULL,
	[Opc] [bit] NULL,
	[idOperadora] [int] NULL,
	[FechaGestionOp] [datetime] NULL,
	[idCre_GestionCredito] [int] NULL,
	[Reliquido] [bit] NULL,
	[UsuarioReliquido] [varchar](50) NULL,
	[FechaReliquido] [datetime] NULL,
	[NGAF_Pichincha] [varchar](20) NULL,
	[EstadoCrediPoint] [int] NULL,
	[Confirmado] [bit] NULL,
	[Confirmado1] [bit] NULL,
	[Confirmado2] [bit] NULL,
	[NumeroDeOperacion] [varchar](20) NULL,
	[Cuotas_Locales] [int] NULL,
	[Cuotas_Vendidas] [int] NULL,
	[CapitalVendido] [decimal](18, 2) NULL,
	[FechaVenta] [datetime] NULL,
	[NumeroDeCredito] [varchar](50) NULL,
	[Verificador] [bit] NULL,
	[Solicitud] [bit] NULL,
	[Cedula] [bit] NULL,
	[Pagare] [bit] NULL,
	[Amortizacion] [bit] NULL,
	[GastosDeCobranza] [bit] NULL,
	[LugarDePago] [bit] NULL,
	[Factura] [bit] NULL,
	[IngresosGastos] [bit] NULL,
	[ReservaDeDominio] [bit] NULL,
	[NotasRecepcionDoc] [varchar](1000) NULL,
	[UsuarioRecepcion] [varchar](50) NULL,
	[RecepcionDocs] [datetime] NULL,
	[EstadoCredito] [int] NULL,
	[CheckList] [bit] NULL,
	[EstadoEPC] [int] NULL,
	[UsuarioEPC] [varchar](50) NULL,
	[FechaEPC] [datetime] NULL,
	[NotasEPC] [varchar](1000) NULL,
	[NotasRechazoBanco] [varchar](1000) NULL,
	[ObservacionesCarpa] [varchar](8000) NULL,
	[idGarantiaExtendida] [int] NULL,
	[FondoGarantia] [bit] NULL,
	[FechaDebito] [datetime] NULL,
	[ValorDebito] [decimal](18, 2) NULL,
	[UsuarioDebito] [varchar](50) NULL,
	[EstacionDebito] [varchar](50) NULL,
	[FechaUsuarioDebito] [datetime] NULL,
	[Verificacion] [bit] NULL,
	[NotasAprobadoVerificacion] [varchar](300) NULL,
	[NotasVerificacion] [varchar](300) NULL,
	[NumTransaccion] [varchar](20) NULL,
	[NumGuia] [varchar](20) NULL,
	[FormaEnvio] [int] NULL,
	[ValorEnvio] [decimal](18, 2) NULL,
	[idProveedor] [int] NULL,
	[DireccionEntrega] [varchar](200) NULL,
	[DescuentoFactura] [decimal](18, 2) NULL,
	[Jornada] [decimal](18, 2) NULL,
	[ClienteNombre] [varchar](1000) NULL,
	[ComisionLote] [decimal](18, 2) NULL,
	[Contribucion_Solca] [decimal](18, 2) NULL,
	[ValorAcreditado] [decimal](18, 2) NULL,
	[Jornadas] [int] NULL,
	[Encuesta] [int] NULL,
	[OtrosEncuesta] [varchar](100) NULL,
	[DiasCredito3] [int] NULL,
	[idFE_EstadoComprobante] [int] NULL,
	[Personas] [int] NULL,
	[Responsablecurier] [varchar](100) NULL,
	[FecEntCurier] [datetime] NULL,
	[FacturaDeCarpa] [int] NULL,
	[FondoDeGarantia] [decimal](18, 2) NULL,
	[EstadoRefinanciacion] [int] NULL,
	[FechaRefinanciacion] [datetime] NULL,
	[ValorRefinanciado] [decimal](18, 2) NULL,
	[idResponsableDocs] [int] NULL,
	[UsuarioRefinancia] [varchar](50) NULL,
	[CaducaRefinanciacion] [datetime] NULL,
	[Asignado] [int] NULL,
	[A_Fecha] [datetime] NULL,
	[A_DiasVencidos] [int] NULL,
	[A_PorVencer] [decimal](18, 2) NULL,
	[A_Vencido] [decimal](18, 2) NULL,
	[A_Gastos] [decimal](18, 2) NULL,
	[A_Mora] [decimal](18, 2) NULL,
	[A_Valor] [decimal](18, 2) NULL,
	[A_Cobrado] [decimal](18, 2) NULL,
	[A_Usuario] [varchar](50) NULL,
	[ObservacionesRefin] [varchar](1000) NULL,
	[FechaRefEntregaDocs] [datetime] NULL,
	[FechaEnvioSRI] [datetime] NULL,
	[FechaAutorizacionSRI] [datetime] NULL,
	[MensajeSRI_1] [varchar](1000) NULL,
	[MensajeSRI_2] [varchar](1000) NULL,
	[MensajeSRI_3] [varchar](1000) NULL,
	[MensajeSRI_4] [varchar](1000) NULL,
	[FechaTransitoLote] [datetime] NULL,
	[idCbo_GestionesDeCobranzas] [int] NULL,
	[EstadoSolNC] [int] NULL,
	[FechaSolicitudNC] [datetime] NULL,
	[FechaAprobacionNC] [datetime] NULL,
	[UsuarioAutoriza] [varchar](50) NULL,
	[CompromisoPago] [bit] NULL,
	[Seguro] [bit] NULL,
	[RetornaPoint] [int] NULL,
	[NotasRetornoPoint] [varchar](300) NULL,
	[FechaRetornoPoint] [datetime] NULL,
	[UsuarioRetornoPoint] [varchar](50) NULL,
	[CuotasVencidasRetornoPoint] [int] NULL,
	[DiasMoraRetornoPoint] [int] NULL,
	[CapitalRetornoPoint] [decimal](18, 2) NULL,
	[InteresRetornoPoint] [decimal](18, 2) NULL,
	[MoraRetornoPoint] [decimal](18, 2) NULL,
	[ValorPrecancelacionRetornoPoint] [decimal](18, 2) NULL,
	[DFI] [bit] NULL,
	[idCobranzaExterna] [int] NULL,
	[InteresRPPrec] [decimal](18, 2) NULL,
	[MoraRPPrec] [decimal](18, 2) NULL,
	[SeguroDFI] [int] NULL,
	[EstadoSeguro] [int] NULL,
	[NumEncuesta] [varchar](300) NULL,
	[Puntos] [int] NULL,
	[Correo] [varchar](100) NULL,
	[NumEncuestaDos] [varchar](100) NULL,
	[Preventa] [bit] NULL,
	[AbonaCuota] [bit] NULL,
	[DiferidoBanco] [bit] NULL,
	[IntFDG] [decimal](18, 2) NULL,
	[FDGUltimo] [bit] NULL,
	[dPorcDescGastos] [decimal](18, 2) NULL,
	[dPorcDescMora] [decimal](18, 2) NULL,
	[iCuotaRef] [int] NULL,
	[dValorRef] [decimal](18, 2) NULL,
	[dTotalGastos] [decimal](18, 2) NULL,
	[dTotalMora] [decimal](18, 2) NULL,
	[FechaPrimeraRef] [datetime] NULL,
	[FechaPeriodo] [datetime] NULL,
	[idCuenta] [int] NULL,
	[bAprobadoODC] [bit] NULL,
	[dTPeriodo] [bit] NULL,
	[Periodo] [date] NULL,
	[FechaReCompra] [datetime] NULL,
	[UrlCompartido] [varchar](500) NULL,
	[UrlNube] [varchar](500) NULL,
	[iEstadoGoogle] [int] NULL,
	[UrlGoogle] [varchar](500) NULL,
	[DiasCredito4] [int] NULL,
	[FechaEmision] [datetime] NULL,
	[bLiquidacionCob] [bit] NULL,
	[bBonoGarantias] [bit] NULL,
	[FechaBono] [datetime] NULL,
	[UsuarioBono] [varchar](50) NULL,
	[bColateral] [bit] NULL,
	[Cartera] [int] NULL,
	[ValidaRecurrente] [bit] NULL,
	[NumeroActa] [varchar](10) NULL,
	[SelDocumentoEnviado] [bit] NULL,
	[ValorDocumentoEnviado] [decimal](18, 4) NULL,
	[SeguroALiquidar] [bit] NULL,
	[DepositoDeducible] [bit] NULL,
	[idArticuloOriginal] [int] NULL,
	[idCompraProtegidaOrigen] [int] NULL,
	[iFreelance] [int] NULL,
	[iODC] [int] NULL,
	[InteresDevInt] [decimal](18, 2) NULL,
	[idCre_SolicitudWeb] [int] NULL,
	  */}

import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Compra')
export class Compra {
	@PrimaryGeneratedColumn()
    idCompra: number;

    @Column({ type: 'int', nullable: true })
    idCre_SolicitudWeb: number;

	@Column({ type: 'datetime', nullable: true })
    Fecha: Date;

	@Column({ length: 50, nullable: true })
    Numero: string;

	@Column({ type: 'decimal', precision: 18, scale: 2, nullable: true })
    Total: number;

    @Column({ type: 'decimal', precision: 18, scale: 2, nullable: true})
    CuotaEntrada: number;

    @Column({ type: 'int', nullable: true })
    NumCuotas: number;

	@Column({ length: 15, nullable: true })
    Ruc: string;

    @Column({ type: 'int', nullable: true })
    idTipoFactura: number;

	@Column({ type: 'int', nullable: true })
	idFormaPago: number;

	@Column({ type: 'int', nullable: true })
	Estado: number;

	@Column({ type: 'bit', nullable: true })
	Borrar: boolean;

	@Column({ type: 'int', nullable: true })
	Bodega: number;

	@Column({ type: 'datetime', nullable: true })
    FechaIngreso: Date;

}
